NegasiQuanta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('portfolio_page.urls')),
    path('message/', include('msg.urls'))
]

msg/urls.py
from . import views
from django.urls import path

app_name = 'msg'

urlpatterns = [
    path('', views.message_list, name='message_list'),
    path('message_create/', views.message_create, name="message_create")
]

portfolio_page/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='portfolio_page'
urlpatterns = [
    path('', views.index, name='homepage')
]

msg/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    submitter = models.CharField(max_length=50)
    msg = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return "{} - {}".format(self.submitter, self.snipped_message())
    
    def snipped_message(self):
        if len(self.msg) > 20 :
            return self.msg[:20] + " ..."
        return self.msg

portfolio_page/models.py
from django.db import models

# Create your models here.

msg/forms.py
from . import models
from django import forms

class CreateMessageForm(forms.Form):
    submitter = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "fields",
        "required" : True,
        "placeholder" : "Your Name",
        }), max_length=50)

    message = forms.CharField(widget=forms.Textarea(attrs={
        "class" : "fields",
        "required" : True,
        "placeholder" : "Your Message Here",
        }), max_length=50)

class Meta:
    model = models.Message

msg/views.py
from django.shortcuts import render, redirect
from .models import Message
from . import forms

def message_create(request):
    message_form = forms.CreateMessageForm(request.POST)
    if request.method == "POST" and message_form.is_valid():
        Message.objects.create(
            submitter = message_form.cleaned_data['submitter'],
            msg =message_form.cleaned_data['message']
        )
    return redirect('msg:message_list')

def message_list(request):
    messages = Message.objects.all()
    message_form = forms.CreateMessageForm()
    response = {
        'msgs' : messages,
        'form' : message_form
    }
    return render(request, 'msg/message_list.html',response)

portfolio_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "portfolio_page/Web profile.html")

msg/templates/msg/message_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <form action = "{% url 'msg:message_create'%}" method = "POST">
        {% csrf_token %}
        <div>
            {% for field in form.visible_fields %}
                {{ field }}
            {% endfor %}
        </div>
        <button type="submit">ADD!</button>
    </form>
    {% for message in msgs %}
    <h6> {{ message.submitter}}</h6>
    <p> {{ message.msg }} </p>
    <p> {{ message.created_at }} </p>
    {% endfor %}
</body>
</html>

portfolio_page/templates/portfolio_page/Web profile.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'portfolio_page/style.css' %}" >
    <title>Zuhdi's Web</title>
</head>

<body>
<header>
    <div class="container">
        <img src="{% static 'portfolio_page/logo43.png' %}" alt="logo" class="logo">

        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#profile">Profile</a></li>
                <li><a href="#snh">S & H</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </div>
</header>
<div class="content" id="contentbg">
    <div class="detail" id="home">
        <h1><pre>W E L C O M E</pre></h1>
        <h1><pre>T O</pre></h1>
        <h1><pre>Z U H D I 'S  W E B</pre></h1>
        <p><img src="{% static 'portfolio_page/line2.png' %}" alt="line" class="line"></p>
    </div>
    <div class="detail" id="profile">
        <div id="ftprof">
            <p><img src="{% static 'portfolio_page/foto.jpg' %}" alt="Foto" class="foto"></p>
        </div>
        <div id="pg">
            <p>My name is Muhammad Zuhdi Zamrud<br>I am 18 years old<br>I was born in Bekasi</p>
            <img src="{% static 'portfolio_page/line2.png' %}" alt="line" class="line">
        </div>
    </div>
    <div class="detail" id="snh">
        <p>SKILLS</p>
        <div id="dtl">
            <p><img src="{% static 'portfolio_page/code.jpg' %}" alt="code" class="code"></p>
            CODING
        </div>
        <div id="dtl">
            <p><img src="{% static 'portfolio_page/gaming.jpg' %}" alt="gaming" class="gaming"></p>
            GAMING
        </div>
        <p>HOBBIES</p>
        <div id="dtl">
            adsad
        </div>
        <div id="dtl">
            asdada
        </div> 
        <p><img src="{% static 'portfolio_page/line2.png' %}" alt="line" class="line"></p>
    </div>
    <div class="detail" id="contact">
            <p>Contact</p>
    </div>
</div>
</body>

</html>